const fs = require("fs");
let code = fs.readFileSync("client/src/pages/NewsFeed.jsx", "utf8");
code = code.replace('<div className="absolute inset-0 bg-white/85 backdrop-blur-[2px] z-0" />', '');
code = code.replace(/text-black/g, "text-white");
code = code.replace(/text-red-700/g, "text-red-400");
code = code.replace(/bg-red-100/g, "bg-red-500/20");
code = code.replace(/border-red-200/g, "border-red-500/30");
code = code.replace(/text-orange-700/g, "text-orange-400");
code = code.replace(/bg-orange-100/g, "bg-orange-500/20");
code = code.replace(/border-orange-200/g, "border-orange-500/30");
code = code.replace(/text-yellow-700/g, "text-yellow-400");
code = code.replace(/bg-yellow-100/g, "bg-yellow-500/20");
code = code.replace(/border-yellow-200/g, "border-yellow-500/30");
code = code.replace(/bg-white\/70 border border-white/g, "liquid-glass");
code = code.replace(/bg-white\/80 backdrop-blur-md/g, "liquid-glass");
code = code.replace(/bg-white\/70 backdrop-blur-xl border border-white\/80/g, "liquid-glass placeholder:text-white/50");
code = code.replace(/border-black\/10/g, "border-white/20");
code = code.replace(/border-black\/5/g, "border-white/10");
code = code.replace(/bg-black text-white/g, "bg-white text-black");
code = code.replace(/bg-black\/\[0\.03\]/g, "bg-white/10");
code = code.replace(/bg-black\/5/g, "bg-white/10");
code = code.replace(/border-t-black/g, "border-t-white");
fs.writeFileSync("client/src/pages/NewsFeed.jsx", code);
